### ISSUE TITLE
账号已锁，麻烦帮忙解锁下

### ISSUE THREAD

**Issue by eicoder** [v2ss/shadowrocket#26]

**Comment by Vikingwangsyx** [comment]
Please unlock apple id

**Comment by Vikingwangsyx** [comment]
I could support the official version to buy it in store, But it must pay in app store in external app store, for instance, hong kong. I can’t buy that, because i’m in different area. Could you provide a way that We can pay it by another way - website. and can freely download it in app store in any area.

**Comment by v2ss** [comment]
fix 

> I could support the official version to buy it in store, But it must pay in app store in external app store, for instance, hong kong. I can’t buy that, because i’m in different area. Could you provide a way that We can pay it by another way - website. and can freely download it in app store in any area.

fix, Can help you, can appreciate a cup of coffee！

**Comment by Vikingwangsyx** [comment]
Hi team
the apple id xb2a1303@icloud.com is still locked

发自Viking 的iPad

在 2020年2月29日，12:54，掠影网络 <notifications@github.com> 写道：

﻿

fix

I could support the official version to buy it in store, But it must pay in app store in external app store, for instance, hong kong. I can’t buy that, because i’m in different area. Could you provide a way that We can pay it by another way - website. and can freely download it in app store in any area.

fix, Can help you, can appreciate a cup of coffee！
